export const ASSIGNMENT_STATUS = Object.freeze({
  NOT_SUBMITTED: "not_submitted",
  DRAFT: "draft",
  SUBMITTED: "submitted",
  UNDER_REVIEW: "under_review",
  APPROVED: "approved",
  GRADED: "graded",
  REJECTED: "rejected",
  RESUBMISSION_REQUIRED: "resubmission_required",
  PENDING_VERIFICATION: "pending_verification",
  RESUBMITTED: "resubmitted",
  RETURNED: "returned",
});

const STATUS_ALIASES = {
  [ASSIGNMENT_STATUS.NOT_SUBMITTED]: ASSIGNMENT_STATUS.NOT_SUBMITTED,
  [ASSIGNMENT_STATUS.DRAFT]: ASSIGNMENT_STATUS.DRAFT,
  [ASSIGNMENT_STATUS.SUBMITTED]: ASSIGNMENT_STATUS.SUBMITTED,
  [ASSIGNMENT_STATUS.UNDER_REVIEW]: ASSIGNMENT_STATUS.UNDER_REVIEW,
  [ASSIGNMENT_STATUS.APPROVED]: ASSIGNMENT_STATUS.APPROVED,
  [ASSIGNMENT_STATUS.GRADED]: ASSIGNMENT_STATUS.GRADED,
  [ASSIGNMENT_STATUS.REJECTED]: ASSIGNMENT_STATUS.REJECTED,
  [ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED]: ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED,
  [ASSIGNMENT_STATUS.PENDING_VERIFICATION]: ASSIGNMENT_STATUS.UNDER_REVIEW,
  [ASSIGNMENT_STATUS.RESUBMITTED]: ASSIGNMENT_STATUS.UNDER_REVIEW,
  [ASSIGNMENT_STATUS.RETURNED]: ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED,
  idle: ASSIGNMENT_STATUS.NOT_SUBMITTED,
  loading: ASSIGNMENT_STATUS.NOT_SUBMITTED,
  error: ASSIGNMENT_STATUS.NOT_SUBMITTED,
  submitted: ASSIGNMENT_STATUS.SUBMITTED,
  pending_verification: ASSIGNMENT_STATUS.UNDER_REVIEW,
  resubmitted: ASSIGNMENT_STATUS.UNDER_REVIEW,
  approved: ASSIGNMENT_STATUS.APPROVED,
  graded: ASSIGNMENT_STATUS.GRADED,
  rejected: ASSIGNMENT_STATUS.REJECTED,
  returned: ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED,
  draft: ASSIGNMENT_STATUS.DRAFT,
};

const STATUS_LABELS = {
  [ASSIGNMENT_STATUS.NOT_SUBMITTED]: "Not submitted",
  [ASSIGNMENT_STATUS.DRAFT]: "Draft saved",
  [ASSIGNMENT_STATUS.SUBMITTED]: "Submitted - Awaiting Review",
  [ASSIGNMENT_STATUS.UNDER_REVIEW]: "Under Review",
  [ASSIGNMENT_STATUS.APPROVED]: "Approved",
  [ASSIGNMENT_STATUS.GRADED]: "Graded",
  [ASSIGNMENT_STATUS.REJECTED]: "Rejected",
  [ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED]: "Resubmission Required",
};

export function normalizeAssignmentStatus(status) {
  return STATUS_ALIASES[String(status || "").trim().toLowerCase()] || ASSIGNMENT_STATUS.NOT_SUBMITTED;
}

export function getAssignmentStatusLabel(status) {
  return STATUS_LABELS[normalizeAssignmentStatus(status)] || STATUS_LABELS[ASSIGNMENT_STATUS.NOT_SUBMITTED];
}

export function canResubmitAssignment(status) {
  const normalized = normalizeAssignmentStatus(status);
  return normalized === ASSIGNMENT_STATUS.DRAFT || normalized === ASSIGNMENT_STATUS.REJECTED || normalized === ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED;
}

export function canEditAssignment(status) {
  const normalized = normalizeAssignmentStatus(status);
  return normalized === ASSIGNMENT_STATUS.NOT_SUBMITTED || normalized === ASSIGNMENT_STATUS.DRAFT || normalized === ASSIGNMENT_STATUS.REJECTED || normalized === ASSIGNMENT_STATUS.RESUBMISSION_REQUIRED;
}
