#!/bin/bash
set -euo pipefail

: "${TELITE_POSTGRES_DB:=telite_backend}"
: "${TELITE_POSTGRES_USER:=telite_backend_user}"
: "${TELITE_POSTGRES_PASSWORD:?TELITE_POSTGRES_PASSWORD must be set for database bootstrap}"

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${TELITE_POSTGRES_USER}') THEN
            CREATE ROLE ${TELITE_POSTGRES_USER} LOGIN PASSWORD '${TELITE_POSTGRES_PASSWORD}';
        ELSE
            ALTER ROLE ${TELITE_POSTGRES_USER} WITH LOGIN PASSWORD '${TELITE_POSTGRES_PASSWORD}';
        END IF;
    END
    \$\$;

    SELECT 'CREATE DATABASE ${TELITE_POSTGRES_DB} OWNER ${TELITE_POSTGRES_USER}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${TELITE_POSTGRES_DB}') \gexec

    REVOKE ALL ON DATABASE ${TELITE_POSTGRES_DB} FROM PUBLIC;
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${TELITE_POSTGRES_DB}" <<-EOSQL
    GRANT ALL ON SCHEMA public TO ${TELITE_POSTGRES_USER};
EOSQL
