"""remove_duplicate_role_permissions_constraints

Revision ID: 262cdd79253b
Revises: 957db1491480
Create Date: 2026-08-01 12:55:47.292421

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262cdd79253b'
down_revision: Union[str, None] = '957db1491480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove duplicate unique constraint on role_permissions
    # Original: role_permissions_org_id_role_permission_key_key (created by a5f001_platform_schema_normalization with UNIQUE constraint)
    # Duplicate: uq_role_permissions_org_role_permission (created by 957db1491480)
    op.drop_constraint('uq_role_permissions_org_role_permission', 'role_permissions')
    
    # Remove duplicate foreign key on role_permissions
    # Original: role_permissions_org_id_fkey (auto-generated by REFERENCES in a5f001_platform_schema_normalization)
    # Duplicate: fk_role_permissions_org_id_organizations (explicitly named in recent migration)
    op.drop_constraint('fk_role_permissions_org_id_organizations', 'role_permissions')


def downgrade() -> None:
    # Restore the duplicate unique constraint
    op.create_unique_constraint('uq_role_permissions_org_role_permission', 'role_permissions', ['org_id', 'role', 'permission_key'])
    
    # Restore the duplicate foreign key
    op.create_foreign_key('fk_role_permissions_org_id_organizations', 'role_permissions', ['org_id'], 'organizations', ['id'])
