"""phase_d_quiz_engine

Revision ID: 2b803db5bf76
Revises: 417f828b3e0a
Create Date: 2026-06-08 00:00:39.596320

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b803db5bf76'
down_revision: Union[str, None] = '417f828b3e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_rubrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_rubrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_rubrics_org_id'), ['org_id'], unique=False)

    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_banks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_banks_org_id'), ['org_id'], unique=False)

    op.create_table('rubric_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['grading_rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rubric_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rubric_criteria_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rubric_criteria_rubric_id'), ['rubric_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['question_versions.id'], name='fk_question_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_org_id'), ['org_id'], unique=False)

    op.create_table('question_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('correct_answer_json', sa.JSON(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_versions_question_id'), ['question_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('tab_switch_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('attempt_limit', sa.Integer(), nullable=True),
    sa.Column('show_answers', sa.String(length=50), nullable=True),
    sa.Column('show_score', sa.String(length=50), nullable=True),
    sa.Column('shuffle_questions', sa.Integer(), nullable=True),
    sa.Column('shuffle_options', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('review_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_settings_quiz_id'), ['quiz_id'], unique=True)

    op.create_table('grading_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('grader_id', sa.String(length=50), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('new_score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['grader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_events_grader_id'), ['grader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_events_org_id'), ['org_id'], unique=False)

    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Float(), nullable=True),
    sa.Column('instructor_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_question_version_id'), ['question_version_id'], unique=False)

    op.create_table('quiz_attempt_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempt_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_events_org_id'), ['org_id'], unique=False)

    op.create_table('quiz_attempt_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempt_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_questions_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_questions_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_questions_question_version_id'), ['question_version_id'], unique=False)


def downgrade() -> None:
    op.drop_table('quiz_attempt_questions')
    op.drop_table('quiz_attempt_events')
    op.drop_table('quiz_answers')
    op.drop_table('grading_events')
    op.drop_table('quiz_settings')
    op.drop_table('quiz_attempts')
    op.drop_table('question_versions')
    op.drop_table('questions')
    op.drop_table('rubric_criteria')
    op.drop_table('question_banks')
    op.drop_table('grading_rubrics')
