"""media_asset_usages

Revision ID: c99c89b4b321
Revises: g7c9d4e1f236
Create Date: 2026-06-23 11:21:36.797665

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c99c89b4b321'
down_revision: Union[str, None] = 'g7c9d4e1f236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_asset_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('usage_context', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_asset_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_usages_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_usages_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_usages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_usages_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_asset_usages_org_id'), ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_asset_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_asset_usages_org_id'))
        batch_op.drop_index(batch_op.f('ix_media_asset_usages_media_asset_id'))
        batch_op.drop_index(batch_op.f('ix_media_asset_usages_id'))
        batch_op.drop_index(batch_op.f('ix_media_asset_usages_entity_type'))
        batch_op.drop_index(batch_op.f('ix_media_asset_usages_entity_id'))

    op.drop_table('media_asset_usages')
    # ### end Alembic commands ###
